### ISSUE TITLE
Why does the guide recommend using loopback devices?

### ISSUE THREAD

**Issue by xanoni** [keks24/raspberry-pi-luks#4]
Keks, I diverged somewhat from the guide and operated on the target SSD directly. I think it worked fine. Is there any particular reason why you suggest using the loopback devices?

**Comment by keks24** [comment]
> Is there any particular reason why you suggest using the loopback devices?

Yes, there is.

The guide is about encrypting the `Raspberry Pi OS Lite image` from [their official website](https://www.raspberrypi.org/software/operating-systems/) and not about encrypting other hard drives. When I was writing the guide, I noticed, that it drifted a bit away from the actual topic and I jokingly thought about writing a guide about `LUKS`, since it was getting into `LUKS-related` details.
I kept it like that, which makes it a bit more applicable for other use cases.

I preferred using loopback devices, since it is easier to mount overlapping device partitions. It is more likely to get the error `overlapping loop device exists`, if using `mount`. For example:

```bash
$ mount "/dev/mmcblk0p2" "/mnt/"
$ mount "/dev/mmcblk0p1" "/mnt/boot/"
overlapping loop device exists
```

However, you can use `mount` in order to have overlapping mounts, but for this, you have to do some calculations with the `start` and `end sector` of the partitions, which I cannot remember anymore. It was annoying and would unnecessarily extend the guide.

Anyways, using `loopback devices` is required to decrypt the second partition of the image like so:

```bash
$ parted "raspberrypi_sd_card_backup.img" "unit s print"
Model:  (file)
Disk /root/tmp/raspberrypi_sd_card_backup.img: 31116288s
Sector size (logical/physical): 512B/512B
Partition Table: msdos
Disk Flags:

Number  Start    End        Size       Type     File system  Flags
 1      8192s    532479s    524288s    primary  fat32        lba
 2      532480s  15523839s  14991360s  primary
$ losetup --offset="$(( 512 * 532480 ))" "/dev/loop2" "raspberrypi_sd_card_backup.img"
$ cryptsetup open "/dev/loop2" cryptsdcard
Enter passphrase for /dev/loop2: raspberry
$ mount "/dev/mapper/cryptsdcard" "/mnt/"
```

You cannot use `mount` for this.

-Keks

**Comment by xanoni** [comment]
Okay. I just encrypted my /dev/sda2 (SSD /root) directly via cryptsetup and then copied over the files from the mounted SD card. So that's why I never used a loopback device.
